### ISSUE TITLE
Exception in localAssemblyWithDBGAlgorithm - Unable to get kmer

### ISSUE THREAD

**Issue by pontushojer** [anne-gcd/MTG-Link#28]
Just at the start of the assembly step I get a few exceptions like this. 
```
STEP 3/3: Local Assembly MTG-Link (Local Assembly and Qualitative Evaluation steps)

File 'localAssemblyDBG.py, function 'localAssemblyWithDBGAlgorithm()': Unable to get the left kmer for chr1.
File 'localAssemblyDBG.py, function 'localAssemblyWithDBGAlgorithm()': Unable to get the left kmer for chr1.
File 'localAssemblyDBG.py, function 'localAssemblyWithDBGAlgorithm()': Unable to get the left kmer for chr1.
File 'localAssemblyDBG.py, function 'localAssemblyWithDBGAlgorithm()': Unable to get the left kmer for chr1.
LOCAL ASSEMBLY OF: chr4_52130209-54617256-L+_chr4_54617356-55746003-R+ for k=51 and a=3 (union)
```

- What is the significance of this error? If one of the left or right kmer cannot be found, will the assembly still be attempted for the affected gap/insertion?
- Is there any way to fix this, for example by changing kmer lengths?

**Comment by clemaitre** [comment]
Hi Pontus,

This is not an error (although the message I agree looks like an error), just a warning and the program keeps trying to perform the assembly with other k values.
The left and right kmers are retrieved from the mapped reads in the flanking regions (to ensure the starting kmer is really present in the input read file), this message can happen when there is no mapped read at the corresponding position. In this case the program continues with other k values.

I have corrected the message which is now more explicit and made it appear as a warning instead of an error. I have also modified a bit the behavior : if no suitable kmer can be found in the mapped reads, then the kmer from the reference sequence is used instead.

Best,
Claire

**Comment by pontushojer** [comment]
> This is not an error (although the message I agree looks like an error), just a warning and the program keeps trying to perform the assembly with other k values. The left and right kmers are retrieved from the mapped reads in the flanking regions (to ensure the starting kmer is really present in the input read file), this message can happen when there is no mapped read at the corresponding position. In this case the program continues with other k values.

Thanks for the clarification!
 
> I have corrected the message which is now more explicit and made it appear as a warning instead of an error. I have also modified a bit the behavior : if no suitable kmer can be found in the mapped reads, then the kmer from the reference sequence is used instead.

In the case where the kmer from reference is used, I would guess this kmer is still not present among the reads, right? Would it still possible to reassemble the region for this k-value? From my understanding the left/right kmers are used to direct the path through the DeBrujin graph. Wont this particular kmer be guaranteed to be missing from that graph?

**Comment by clemaitre** [comment]
Yes, the chances are very low that using the reference kmers will allow correct assembly. As you correctly understood, if the reference kmers are absent from the reads, the assembly will still fail. But, we can imagine a situation where there are reads containing these kmers but the whole reads themselves were not mapped at this position for some reason (for instance, a too large part of the reads can not be mapped here).

A more promising way to try to improve the assembly is to modify the gap coordinates (input gfa file or `-ext` parameter) and try to assemble the target sequence starting and ending at slighlty different positions.
